"""
全局常量。所有模块从此导入，一处修改全局生效。
"""
# ── 时间 ──
SECONDS_PER_DAY = 86400

# ── 情绪 ──
EMOTION_SAVE_MIN_INTERVAL = 300  # 两次情绪保存最小间隔（秒）
EMOTION_RECENT_DAYS = 7
EMOTION_RECENT_LIMIT = 3
EMOTION_OLDER_DAYS = 90
EMOTION_OLDER_LIMIT = 2
EMOTION_MAX_TEXT_LEN = 200
EMOTION_ARCHIVE_DAYS = 365  # 超过此天数自动降级为 B 级

# ── 提醒 ──
REMINDER_AHEAD_SECONDS = 86400  # 提前 1 天查询到期提醒
REMINDER_MAX_TEXT_LEN = 200
REMINDER_DEDUP_WINDOW = 86400  # 去重窗口（秒）

# ── 主动行为 ──
ACTIVE_MAX_PER_DAY = 2
ACTIVE_MISSING_HOURS_PEAK = 48  # 思念度达到峰值的时长
ACTIVE_BASE_PROBABILITY = 0.25
ACTIVE_QUIET_START_HOUR = 6  # 免打扰开始时间
ACTIVE_DAILY_COUNT_RESET_HOUR = 0  # 每日计数重置时间
